version: "3"
services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/lampLemp.lan.conf:/etc/apache2/sites-enabled/lampLemp.lan.conf
      - ./apache/certificados:/certificados

  bd:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - datos:/var/lib/mysql
      - ./bd:/backup
      - ./bd:/docker-entrypoint-initdb.d

volumes:
  datos:
